package beans;
// Generated Apr 26, 2017 2:26:31 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="arkancafe"
)
public class Category  implements java.io.Serializable {


     private Integer catId;
     private Tab tab;
     private String catName;
     private Set items = new HashSet(0);

    public Category() {
    }

	
    public Category(Tab tab, String catName) {
        this.tab = tab;
        this.catName = catName;
    }
    public Category(Tab tab, String catName, Set items) {
       this.tab = tab;
       this.catName = catName;
       this.items = items;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cat_id", unique=true, nullable=false)
    public Integer getCatId() {
        return this.catId;
    }
    
    public void setCatId(Integer catId) {
        this.catId = catId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tab_id", nullable=false)
    public Tab getTab() {
        return this.tab;
    }
    
    public void setTab(Tab tab) {
        this.tab = tab;
    }

    
    @Column(name="cat_name", nullable=false, length=50)
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


