package beans;
// Generated Apr 26, 2017 2:26:31 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemIngredient generated by hbm2java
 */
@Entity
@Table(name="item_ingredient"
    ,catalog="arkancafe"
)
public class ItemIngredient  implements java.io.Serializable {


     private ItemIngredientId id;
     private Ingredient ingredient;
     private Item item;
     private Unit unit;
     private int quantity;

    public ItemIngredient() {
    }

    public ItemIngredient(ItemIngredientId id, Ingredient ingredient, Item item, Unit unit, int quantity) {
       this.id = id;
       this.ingredient = ingredient;
       this.item = item;
       this.unit = unit;
       this.quantity = quantity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="ingId", column=@Column(name="ing_id", nullable=false) ), 
        @AttributeOverride(name="itemId", column=@Column(name="item_id", nullable=false) ) } )
    public ItemIngredientId getId() {
        return this.id;
    }
    
    public void setId(ItemIngredientId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ing_id", nullable=false, insertable=false, updatable=false)
    public Ingredient getIngredient() {
        return this.ingredient;
    }
    
    public void setIngredient(Ingredient ingredient) {
        this.ingredient = ingredient;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_id", nullable=false, insertable=false, updatable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unit_id", nullable=false)
    public Unit getUnit() {
        return this.unit;
    }
    
    public void setUnit(Unit unit) {
        this.unit = unit;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


