package beans;
// Generated Apr 26, 2017 2:26:31 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ItemIngredientId generated by hbm2java
 */
@Embeddable
public class ItemIngredientId  implements java.io.Serializable {


     private int ingId;
     private int itemId;

    public ItemIngredientId() {
    }

    public ItemIngredientId(int ingId, int itemId) {
       this.ingId = ingId;
       this.itemId = itemId;
    }
   


    @Column(name="ing_id", nullable=false)
    public int getIngId() {
        return this.ingId;
    }
    
    public void setIngId(int ingId) {
        this.ingId = ingId;
    }


    @Column(name="item_id", nullable=false)
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ItemIngredientId) ) return false;
		 ItemIngredientId castOther = ( ItemIngredientId ) other; 
         
		 return (this.getIngId()==castOther.getIngId())
 && (this.getItemId()==castOther.getItemId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIngId();
         result = 37 * result + this.getItemId();
         return result;
   }   


}


