package beans;
// Generated Apr 26, 2017 2:26:31 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderlineAddition generated by hbm2java
 */
@Entity
@Table(name="orderline_addition"
    ,catalog="arkancafe"
)
public class OrderlineAddition  implements java.io.Serializable {


     private Integer id;
     private Addition addition;
     private Orderline orderline;
     private long quantity;

    public OrderlineAddition() {
    }

    public OrderlineAddition(Addition addition, Orderline orderline, long quantity) {
       this.addition = addition;
       this.orderline = orderline;
       this.quantity = quantity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="addition_id", nullable=false)
    public Addition getAddition() {
        return this.addition;
    }
    
    public void setAddition(Addition addition) {
        this.addition = addition;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orderLine_id", nullable=false)
    public Orderline getOrderline() {
        return this.orderline;
    }
    
    public void setOrderline(Orderline orderline) {
        this.orderline = orderline;
    }

    
    @Column(name="quantity", nullable=false, precision=10, scale=0)
    public long getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(long quantity) {
        this.quantity = quantity;
    }




}


