package beans;
// Generated Apr 26, 2017 2:26:31 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name="service"
    ,catalog="arkancafe"
)
public class Service  implements java.io.Serializable {


     private Integer serviceId;
     private Tab tab;
     private String serviceName;
     private String baseUnit;
     private long basePrice;
     private Set serviceLines = new HashSet(0);

    public Service() {
    }

	
    public Service(Tab tab, String serviceName, String baseUnit, long basePrice) {
        this.tab = tab;
        this.serviceName = serviceName;
        this.baseUnit = baseUnit;
        this.basePrice = basePrice;
    }
    public Service(Tab tab, String serviceName, String baseUnit, long basePrice, Set serviceLines) {
       this.tab = tab;
       this.serviceName = serviceName;
       this.baseUnit = baseUnit;
       this.basePrice = basePrice;
       this.serviceLines = serviceLines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="service_id", unique=true, nullable=false)
    public Integer getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tab_id", nullable=false)
    public Tab getTab() {
        return this.tab;
    }
    
    public void setTab(Tab tab) {
        this.tab = tab;
    }

    
    @Column(name="service_name", nullable=false, length=100)
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    
    @Column(name="base_unit", nullable=false, length=25)
    public String getBaseUnit() {
        return this.baseUnit;
    }
    
    public void setBaseUnit(String baseUnit) {
        this.baseUnit = baseUnit;
    }

    
    @Column(name="base_price", nullable=false, precision=10, scale=0)
    public long getBasePrice() {
        return this.basePrice;
    }
    
    public void setBasePrice(long basePrice) {
        this.basePrice = basePrice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="service")
    public Set getServiceLines() {
        return this.serviceLines;
    }
    
    public void setServiceLines(Set serviceLines) {
        this.serviceLines = serviceLines;
    }




}


