package beans;
// Generated Apr 26, 2017 2:26:31 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tables generated by hbm2java
 */
@Entity
@Table(name="tables"
    ,catalog="arkancafe"
)
public class Tables  implements java.io.Serializable {


     private Integer tableId;
     private String tableName;
     private boolean empty;
     private Set orderses = new HashSet(0);

    public Tables() {
    }

	
    public Tables(String tableName, boolean empty) {
        this.tableName = tableName;
        this.empty = empty;
    }
    public Tables(String tableName, boolean empty, Set orderses) {
       this.tableName = tableName;
       this.empty = empty;
       this.orderses = orderses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="table_id", unique=true, nullable=false)
    public Integer getTableId() {
        return this.tableId;
    }
    
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    
    @Column(name="table_name", nullable=false, length=25)
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    
    @Column(name="empty", nullable=false)
    public boolean isEmpty() {
        return this.empty;
    }
    
    public void setEmpty(boolean empty) {
        this.empty = empty;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tables")
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


