package beans;
// Generated Apr 26, 2017 2:26:31 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Unit generated by hbm2java
 */
@Entity
@Table(name="unit"
    ,catalog="arkancafe"
)
public class Unit  implements java.io.Serializable {


     private int unitId;
     private Unit unit;
     private String unitName;
     private int conversion;
     private Set itemIngredients = new HashSet(0);
     private Set units = new HashSet(0);
     private Set ingredients = new HashSet(0);

    public Unit() {
    }

	
    public Unit(int unitId, Unit unit, String unitName, int conversion) {
        this.unitId = unitId;
        this.unit = unit;
        this.unitName = unitName;
        this.conversion = conversion;
    }
    public Unit(int unitId, Unit unit, String unitName, int conversion, Set itemIngredients, Set units, Set ingredients) {
       this.unitId = unitId;
       this.unit = unit;
       this.unitName = unitName;
       this.conversion = conversion;
       this.itemIngredients = itemIngredients;
       this.units = units;
       this.ingredients = ingredients;
    }
   
     @Id 

    
    @Column(name="unit_id", unique=true, nullable=false)
    public int getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(int unitId) {
        this.unitId = unitId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="base_unit_id", nullable=false)
    public Unit getUnit() {
        return this.unit;
    }
    
    public void setUnit(Unit unit) {
        this.unit = unit;
    }

    
    @Column(name="unit_name", nullable=false, length=50)
    public String getUnitName() {
        return this.unitName;
    }
    
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    
    @Column(name="conversion", nullable=false)
    public int getConversion() {
        return this.conversion;
    }
    
    public void setConversion(int conversion) {
        this.conversion = conversion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unit")
    public Set getItemIngredients() {
        return this.itemIngredients;
    }
    
    public void setItemIngredients(Set itemIngredients) {
        this.itemIngredients = itemIngredients;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unit")
    public Set getUnits() {
        return this.units;
    }
    
    public void setUnits(Set units) {
        this.units = units;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unit")
    public Set getIngredients() {
        return this.ingredients;
    }
    
    public void setIngredients(Set ingredients) {
        this.ingredients = ingredients;
    }




}


